# Dictionary Copy

loggerではdicitonary引数をdeep copy するべきか、するべきではないかを判定するために、こちらのノートブックを使って検証する。

## 方法
20個　のitemとvalueを　100x100のnumpy とした dictionary を使って検証。

## 結果

- 通常処理　900 ns ± 9.73 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
- deepcopy　201 µs ± 8.54 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

**参考**
DQN、DDQNではもっと小さい量のディクショナリを使用する。


## 結論
この結果より問題ないと判断する。

In [10]:
from copy import copy, deepcopy
import numpy as np
import string

In [11]:
keys=list(string.ascii_lowercase)

In [19]:
res={}
for i in range(20):
    case=np.random.randint(0,3)
    res[keys[i]] = np.random.randint(0,10,size=(100,100))

In [20]:
for k,v in res.items():
    print(k,v)

a [[5 6 8 ... 0 2 0]
 [9 8 1 ... 9 4 6]
 [5 9 2 ... 8 7 3]
 ...
 [8 0 0 ... 4 7 0]
 [6 2 2 ... 0 1 4]
 [1 1 9 ... 3 7 5]]
b [[7 0 5 ... 7 3 2]
 [5 9 0 ... 9 3 3]
 [7 2 8 ... 3 2 9]
 ...
 [9 0 1 ... 5 2 3]
 [1 5 4 ... 5 1 1]
 [8 9 8 ... 7 9 7]]
c [[2 6 4 ... 1 5 8]
 [8 1 5 ... 4 9 0]
 [8 1 4 ... 4 9 1]
 ...
 [5 7 5 ... 5 9 6]
 [0 8 9 ... 9 8 5]
 [7 9 9 ... 4 2 5]]
d [[4 6 5 ... 1 0 0]
 [2 6 3 ... 7 3 6]
 [7 1 4 ... 0 1 9]
 ...
 [5 4 8 ... 0 1 6]
 [2 7 2 ... 4 6 3]
 [9 1 2 ... 9 0 0]]
e [[9 1 2 ... 3 4 3]
 [1 8 2 ... 4 0 5]
 [7 8 7 ... 9 4 4]
 ...
 [4 9 5 ... 4 7 3]
 [0 6 4 ... 2 8 2]
 [9 3 4 ... 2 9 8]]
f [[5 6 5 ... 9 7 7]
 [9 4 0 ... 1 2 8]
 [3 3 7 ... 5 1 0]
 ...
 [8 2 2 ... 7 1 5]
 [5 1 2 ... 1 0 6]
 [7 7 7 ... 7 1 3]]
g [[0 6 6 ... 1 8 7]
 [8 6 7 ... 7 7 3]
 [6 3 9 ... 6 3 1]
 ...
 [9 5 1 ... 6 7 7]
 [3 5 7 ... 3 1 6]
 [1 7 9 ... 4 8 1]]
h [[7 9 6 ... 1 7 2]
 [1 0 8 ... 9 3 6]
 [4 1 9 ... 0 4 6]
 ...
 [2 3 2 ... 1 7 6]
 [2 0 5 ... 1 8 0]
 [3 1 5 ... 1 2 9]]
i [[5 2 9 ... 8 8 4]
 [2

In [21]:
%timeit y = copy(res)

900 ns ± 9.73 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [22]:
%timeit y = deepcopy(res)

201 µs ± 8.54 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
